export const jobList = [
  {
    role: "Senior Frontend Developer",
    description: "Lead UI development using React, TypeScript, and Tailwind.",
    location: "Chennai",
    type: "Full time",
    status: "closed",
    applicants: 39,
    salaryMin: 20000,
    salaryMax: 30000,
    workMode: "Onsite",
    experience: "5+ Yrs",
    vacancy: 20,
    deadline: "2025-02-28",
    skills: ["Java", "Python", "HTML"],
    assessmentTitle: "Frontend Coding Test",
    assessmentFile: "photo.jpg",
    internalNotes: "Strong portfolio required.",
  },
  {
    role: "Full Stack Developer",
    description: "Work on backend (Node.js) and frontend (React).",
    location: "Bangalore",
    type: "Full time",
    status: "Published",
    applicants: 18,
    salaryMin: 25000,
    salaryMax: 42000,
    workMode: "Hybrid",
    experience: "3-5 Yrs",
    vacancy: 5,
    deadline: "2025-03-05",
    skills: ["Node.js", "React", "MongoDB"],
    assessmentTitle: "Full Stack Assignment",
    assessmentFile: "fullstack_test.pdf",
    internalNotes: "Strong API skills preferred.",
  },
  {
    role: "Mobile App Developer",
    description: "Build cross-platform apps using Flutter.",
    location: "Hyderabad",
    type: "Contract",
    status: "Published",
    applicants: 22,
    salaryMin: 15000,
    salaryMax: 28000,
    workMode: "Remote",
    experience: "1-3 Yrs",
    vacancy: 3,
    deadline: "2025-02-25",
    skills: ["Flutter", "Dart", "Firebase"],
    assessmentTitle: "Mobile App Task",
    assessmentFile: "mobile.pdf",
    internalNotes: "Contract for 6 months.",
  },
  {
    role: "Backend Engineer",
    description: "Develop scalable APIs using Django and PostgreSQL.",
    location: "Delhi",
    type: "Full time",
    status: "Published",
    applicants: 12,
    salaryMin: 30000,
    salaryMax: 55000,
    workMode: "Onsite",
    experience: "3-5 Yrs",
    vacancy: 4,
    deadline: "2025-03-10",
    skills: ["Django", "Python", "PostgreSQL"],
    assessmentTitle: "Backend API Test",
    assessmentFile: "backend.pdf",
    internalNotes: "Focus on scalability.",
  },
  {
    role: "Data Scientist",
    description: "Analyze datasets and build ML models.",
    location: "Chennai",
    type: "Full time",
    status: "Published",
    applicants: 20,
    salaryMin: 35000,
    salaryMax: 60000,
    workMode: "Hybrid",
    experience: "1-3 Yrs",
    vacancy: 6,
    deadline: "2025-03-01",
    skills: ["Python", "TensorFlow", "SQL"],
    assessmentTitle: "ML Assessment",
    assessmentFile: "ml_task.docx",
    internalNotes: "Strong stats background.",
  },
  {
    role: "UI/UX Designer",
    description: "Design wireframes, prototypes, and user flows.",
    location: "Bangalore",
    type: "Full time",
    status: "Published",
    applicants: 48,
    salaryMin: 18000,
    salaryMax: 28000,
    workMode: "Remote",
    experience: "1-3 Yrs",
    vacancy: 2,
    deadline: "2025-02-20",
    skills: ["Figma", "Adobe XD", "Prototyping"],
    assessmentTitle: "Design Challenge",
    assessmentFile: "ux.pdf",
    internalNotes: "Portfolio required.",
  },
  {
    role: "DevOps Engineer",
    description: "Manage CI/CD pipelines and cloud infrastructure.",
    location: "Bangalore",
    type: "Full time",
    status: "Published",
    applicants: 33,
    salaryMin: 40000,
    salaryMax: 70000,
    workMode: "Hybrid",
    experience: "3-5 Yrs",
    vacancy: 3,
    deadline: "2025-03-15",
    skills: ["AWS", "Docker", "Kubernetes"],
    assessmentTitle: "DevOps Practical Test",
    assessmentFile: "devops.doc",
    internalNotes: "Must know Terraform.",
  },
  {
    role: "Cybersecurity Analyst",
    description: "Monitor systems and handle security incidents.",
    location: "Chennai",
    type: "Full time",
    status: "Published",
    applicants: 17,
    salaryMin: 32000,
    salaryMax: 52000,
    workMode: "Onsite",
    experience: "1-3 Yrs",
    vacancy: 4,
    deadline: "2025-02-27",
    skills: ["SIEM", "Python", "Network Security"],
    assessmentTitle: "Security Test",
    assessmentFile: "cyber.pdf",
    internalNotes: "Experience with SOC tools required.",
  },
  {
    role: "HR Manager",
    description: "Handle recruitment, payroll, and HR policies.",
    location: "Delhi",
    type: "Full time",
    status: "Published",
    applicants: 10,
    salaryMin: 25000,
    salaryMax: 40000,
    workMode: "Onsite",
    experience: "5+ Yrs",
    vacancy: 1,
    deadline: "2025-03-12",
    skills: ["Communication", "HRMS", "Policy Writing"],
    assessmentTitle: "HR Case Study",
    assessmentFile: "hr.docx",
    internalNotes: "Prefer MBA HR.",
  },
  {
    role: "Marketing Specialist",
    description: "Plan campaigns and manage social media.",
    location: "Delhi",
    type: "Part time",
    status: "Published",
    applicants: 15,
    salaryMin: 12000,
    salaryMax: 20000,
    workMode: "Remote",
    experience: "1-3 Yrs",
    vacancy: 2,
    deadline: "2025-02-22",
    skills: ["SEO", "Content Writing", "Analytics"],
    assessmentTitle: "Marketing Task",
    assessmentFile: "marketing.pdf",
    internalNotes: "Experience with ads required.",
  },
  {
    role: "Cloud Architect",
    description: "Design large-scale cloud solutions.",
    location: "Bangalore",
    type: "Full time",
    status: "Published",
    applicants: 9,
    salaryMin: 50000,
    salaryMax: 80000,
    workMode: "Hybrid",
    experience: "5+ Yrs",
    vacancy: 2,
    deadline: "2025-03-20",
    skills: ["Azure", "AWS", "Architecture"],
    assessmentTitle: "Cloud Architecture Test",
    assessmentFile: "cloud.pdf",
    internalNotes: "Must have multi-cloud experience.",
  },
  {
    role: "Content Writer",
    description: "Write blogs, scripts, and marketing content.",
    location: "Hyderabad",
    type: "Freelance",
    status: "Published",
    applicants: 42,
    salaryMin: 8000,
    salaryMax: 15000,
    workMode: "Remote",
    experience: "Fresher",
    vacancy: 5,
    deadline: "2025-02-18",
    skills: ["Writing", "Research", "SEO"],
    assessmentTitle: "Writing Sample",
    assessmentFile: "content.doc",
    internalNotes: "Must deliver 3 articles per week.",
  },
];
